name: aughovernet
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.11
  - pip=24.1.2
  - openslide
  - pip:
    - -r /cluster/projects/nn12036k/tirilktr/CONIC_Pathology_AI/requirements.txt
    - openslide-python
